ALTER TABLE "User" ADD CONSTRAINT "User_role_check" CHECK ("role" IN ('EMPLOYEE', 'HR'));
ALTER TABLE "User" ADD CONSTRAINT "User_employee_link_check" CHECK ("role" <> 'EMPLOYEE' OR "employeeId" IS NOT NULL);
ALTER TABLE "Grade" ADD CONSTRAINT "Grade_position_check" CHECK ("position" >= 0);
ALTER TABLE "Skill" ADD CONSTRAINT "Skill_type_check" CHECK ("type" IN ('hard', 'soft'));
ALTER TABLE "RoleGradeRequirement" ADD CONSTRAINT "Requirement_level_check" CHECK ("requiredLevel" >= 0 AND "requiredLevel" <= 5);
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_tenure_check" CHECK ("tenureMonths" >= 0);
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_dates_check" CHECK ("lastReviewDate" >= "hireDate");
ALTER TABLE "Employee" ADD CONSTRAINT "Employee_manager_check" CHECK ("managerId" IS NULL OR "managerId" <> "id");
ALTER TABLE "EmployeeSkill" ADD CONSTRAINT "EmployeeSkill_level_check" CHECK ("level" IS NULL OR ("level" >= 0 AND "level" <= 5));
ALTER TABLE "EmployeeDevelopmentState" ADD CONSTRAINT "State_missing_level_check" CHECK ("missingSkillLevel" IS NULL OR ("missingSkillLevel" >= 0 AND "missingSkillLevel" <= 5));
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_duration_check" CHECK ("durationHours" > 0);
ALTER TABLE "Activity" ADD CONSTRAINT "Activity_format_check" CHECK ("format" IN ('online', 'offline', 'self_paced'));
ALTER TABLE "ActivitySkillEffect" ADD CONSTRAINT "Effect_range_check" CHECK ("gain" >= 0 AND "maxLevel" >= 0 AND "maxLevel" <= 5);
ALTER TABLE "ActivityPrerequisite" ADD CONSTRAINT "Prerequisite_level_check" CHECK ("requiredLevel" >= 0 AND "requiredLevel" <= 5);
ALTER TABLE "Participation" ADD CONSTRAINT "Participation_status_check" CHECK ("status" IN ('REGISTERED', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', 'NO_SHOW', 'DECLINED', 'OVERDUE'));
ALTER TABLE "Participation" ADD CONSTRAINT "Participation_completion_check" CHECK ("completionPct" BETWEEN 0 AND 100 AND ("status" <> 'COMPLETED' OR "completionPct" = 100));
ALTER TABLE "Participation" ADD CONSTRAINT "Participation_score_check" CHECK ("score" IS NULL OR "score" BETWEEN 0 AND 100);
ALTER TABLE "Participation" ADD CONSTRAINT "Participation_rating_check" CHECK ("feedbackRating" IS NULL OR "feedbackRating" BETWEEN 1 AND 5);
ALTER TABLE "Participation" ADD CONSTRAINT "Participation_due_check" CHECK ("dueDate" IS NULL OR "dueDate" >= "date");
ALTER TABLE "SkillChange" ADD CONSTRAINT "SkillChange_growth_check" CHECK ("beforeLevel" BETWEEN 0 AND 5 AND "afterLevel" BETWEEN 0 AND 5 AND "actualGain" >= 0 AND "afterLevel" >= "beforeLevel" AND abs("afterLevel" - "beforeLevel" - "actualGain") < 0.000001);
ALTER TABLE "RecommendationItem" ADD CONSTRAINT "RecommendationItem_rank_check" CHECK ("rank" BETWEEN 1 AND 3);
